### PR TITLE
Deploy to GitHub Pages

### PR DESCRIPTION
**Pull request by curran**
Recent activity has been in the `master` branch, but the deployment at http://unhcr.github.io/dataviz draws from the `gh-pages` branch.

This pull request makes the `gh-pages` branch up-to-date with the `master` branch.

Ideally, we could make the `master` branch be the one that deploys to GitHub Pages, and delete the `gh-pages` branch. I don't have contributor access to this repository so I can't do that. @matthewsmawfield Perhaps you could make this change?

### CODE REVIEW

**Comment by curran** [comment]
Closing, as this has been done http://unhcr.github.io/dataviz-population-change/

**Comment by matthewsmawfield** [comment]
@curran i've changed to use master on github pages, so the gh-pages branch could be deleted.

**Comment by curran** [comment]
Great!

**Comment by curran** [comment]
I don't seem to have the right GitHub permissions to delete the remote gh-pages branch. It would be good to delete it though, to avoid any confusion.

**Pull request closed without merging**
